# config.yml

collections:
  - name: "blog" # name of the content type
    label: "Blog Posts"
    folder: "content/blog" # location of the content files
    create: true # allow users to create new items of this content type
    fields: # fields for this content type
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
