# config.yml

collections:
  - name: "blog" # name of the content type
    label: "Blog Posts"
    folder: "content/blog" # location of the content files
    create: true # allow users to create new items of this content type
    fields: # fields for this content type
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
backend:
  name: git-gateway
  branch: dev # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads